### ISSUE TITLE
ApplePay Show [General] Connection to remote alert view service failed

### ISSUE THREAD

**Issue by ibrafayez** [paytabscom/flutter-sdk-bridge#11]
When I try to pay with ApplePay it shows the following **error**:

`
[General] Connection to remote alert view service failed
`

**ApplePay is Active on PayTabs:**
<img width="1102" alt="paytabs_applepay" src="https://user-images.githubusercontent.com/44995398/115283415-fe8dde80-a153-11eb-9773-948cab728f7e.png">

_Also, Apple Pay works on the website but not on the app_

**startApplePayPayment method:**
```
FlutterPaytabsBridge.startApplePayPayment(configuration, (event) {

        if (event["status"] == "success") {
          successPayment();
        } else if (event["status"] == "error") {
          // Handle error here.
          _Result =  'An Error Has Occurred, Please try again later';
        } else if (event["status"] == "event") {
          // Handle events here.
          _Result = "Something went wrong";
        }
    });
```

Note: I removed setState because it shows another error #10

**Comment by mohamedkhairy953** [comment]
We will check it and back to you tomorrow ISA

**Comment by MuhamedAdly** [comment]
Hi @ibrafayez 

If you are using StatefulWidget so you should use setState() to update your widget state, And regarding the issue, it is not related to ApplePay functionality, please try to print the event in your startApplePayPayment or try to run our sample app just to make sure the issue not related to PayTabs flutter plugin.

Waiting for your reply

Thanks

**Comment by ibrafayez** [comment]
I updated flutter_paytabs_bridge to 2.0.4 👍 

I added "print(event)" in startApplePayPayment and I got:
```
[General] Connection to remote alert view service failed
flutter: {status: event, code: 0, message: Cancelled}
```

I also tried your sample app:
On the simulator it works fine (It made me happy at first), but not when I build the app on my phone. 

on my phone I got same error as my project.

![ezgif-7-aea001a6ea00](https://user-images.githubusercontent.com/44995398/115408934-f7b9a700-a1f9-11eb-9be8-199b7aae75d8.gif)



Kind Regards

**Comment by MuhamedAdly** [comment]
did you configure your app for apple pay and merchant id?

**Comment by ibrafayez** [comment]
Yes for my app I configured for ApplePay and added the apple pay id

<img width="1231" alt="Screen Shot 2021-04-20 at 5 18 04 PM" src="https://user-images.githubusercontent.com/44995398/115412281-d73f1c00-a1fc-11eb-9005-7a123062d322.png">

configuration:
<img width="439" alt="Screen Shot 2021-04-20 at 5 23 26 PM" src="https://user-images.githubusercontent.com/44995398/115412762-4d438300-a1fd-11eb-9e32-c1f6e35879da.png">

**Comment by MuhamedAdly** [comment]
send me a message to muhamedadly AT gmail.com or m.adly At paytabs.com to arrange a technical support call.

**Comment by ibrafayez** [comment]
Sent,


Thank you

**Comment by Emadeddin-eibo** [comment]
Any updates on this? I'm having the same error.

**Comment by Musaddiq625** [comment]
> Yes for my app I configured for ApplePay and added the apple pay id
> 
> <img alt="Screen Shot 2021-04-20 at 5 18 04 PM" width="1231" src="https://user-images.githubusercontent.com/44995398/115412281-d73f1c00-a1fc-11eb-9005-7a123062d322.png">
> 
> configuration: <img alt="Screen Shot 2021-04-20 at 5 23 26 PM" width="439" src="https://user-images.githubusercontent.com/44995398/115412762-4d438300-a1fd-11eb-9e32-c1f6e35879da.png">

Hello @MuhamedAdly I'm having the same issue
everything is all set, normal payment is working smoothly
but having 'cancelled' in response on Apple Pay

**Comment by MuhamedAdly** [comment]
Did you follow the steps in the guide to setup Apple Pay certificate:
https://github.com/paytabscom/flutter-sdk-bridge/blob/pt2/ApplePayConfiguration.md

**Comment by Musaddiq625** [comment]
Thanks for the fast response, actually I was just verifying all parameters.
I've found that 'Apple Pay' is not enabled from the paytab dashboard, I've
enabled it, but I think it will take some time.

If that will work or not, I'll get back to you
Thankss

**Comment by Musaddiq625** [comment]
Assalam-o-Alaikum Adly,
yes i've followed the guide
got merchant id, passed all the values, apple pay is now enabled on my
paytab account.
same as this:
[image: image.png]
but still having the same response:
*{status: event, code: 0, *message*: Cancelled}*

Can you please guide me further

Thanks.

**Comment by Musaddiq625** [comment]
atlast.. fixed 😌
Apple pay was disabled on XCode -_-
