### ISSUE TITLE
No Mada card payment option

### ISSUE THREAD

**Issue by junaidlodhi22** [paytabscom/flutter-sdk-bridge#12]
i was about to implement Mada card but I see no option in **PaymentSdkAPms** for Mada card. There is **STCpay**, **UnionPay** but no Mada Card.

if there is a way Kindly let me know. 

Kindly check screenshot from SDK file
<img width="329" alt="Screenshot 2021-06-28 at 12 43 04 PM" src="https://user-images.githubusercontent.com/35798710/123598949-7d675d80-d80e-11eb-89d2-f3a3990f2421.png">

**Comment by AbdelrahmanMohamedEmam** [comment]
Same problem for Fawry and Valu.

**Comment by KhaledAlramam** [comment]
Mada card is supported currently along with fawry and Valu
