### ISSUE TITLE
Apple MetaData Rejected 

### ISSUE THREAD

**Issue by midotaha** [paytabscom/flutter-sdk-bridge#13]
Hi Dears
My Greetings!!
After finished integrate PayTabs Flutter SDK Payment into my Project, Apple Team make it was pending or Metadata Rejected, The reason this is they required more information about NFC features, I do not have properties or other features using the NFC only ApplePay, And I didn't activate this feature at the moment, Is there any way to make the NFC false or not Active?! To show Apple Team that it is inactive?!
👇👇👇👇 this Snapshot from their message 
![Screen Shot 2021-09-11 at 10 26 00 AM](https://user-images.githubusercontent.com/19406537/133042446-d6ee0033-f44f-49c4-801a-9d13b76279c9.png)

**Comment by mohamedkhairy953** [comment]
Hello 

Could you provide me with the SDK version?. for further investigation

**Comment by midotaha** [comment]
`flutter_paytabs_bridge: 2.0.5 ` 
I have provided a video explaining the features of the application, the uses, and the permissions that it has in order to pass the app Review process by the Apple team, and they agreed to this after the required proofs 
But it must be there a code to turn off the NFC in case it is not used, Like the next code for example to turn off the microphone  
 👇👇👇👇👇👇
```
post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
    
    # ADD THE NEXT SECTION
    target.build_configurations.each do |config|
      config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= [
        '$(inherited)',
        'AUDIO_SESSION_MICROPHONE=0'
      ]
    end
  end
end
```

Thank you for your patience

**Comment by midotaha** [comment]
Hi dear , 
News about what @mohadel92 ?!
