### ISSUE TITLE
How Can I found pt_secret_key

### ISSUE THREAD

**Issue by Eng-MohamedGadala** [paytabscom/flutter-sdk-bridge#2]
Hi, dear Developers, I want to thank you for this plugin.
My question how to get pt_secret_key: from the Pay Tabs dashboard after registration I generate secret key and server key but pt_secret_key: not found, how can I get it.

@mohamedkhairy953 
@mustafaanan

**Comment by mustafaanan** [comment]
@Eng-MohamedGadala kindly contact customercare@paytabs.com to provide you with the secret. Please attach your merchant Id in the email.

**Comment by Eng-MohamedGadala** [comment]
> @Eng-MohamedGadala kindly contact [customercare@paytabs.com](mailto:customercare@paytabs.com) to provide you with the secret. Please attach your merchant Id in the email.
Thanks @mustafaanan 
but secret key not found directly on paytables dashbord.

**Comment by devmfouad** [comment]
> @Eng-MohamedGadala kindly contact [customercare@paytabs.com](mailto:customercare@paytabs.com) to provide you with the secret. Please attach your merchant Id in the email.

why i should contact with customer-care 
i think every thing should be clear in documentations

**Comment by mustafaanan** [comment]
@Eng-MohamedGadala There is a system migration process in progress.
If you can wait for few weeks, you will get a new version of mobile SDK without need to customer care support.
If not, customer care can guide you.

**Comment by Eng-MohamedGadala** [comment]
@mustafaanan thanks.
