### ISSUE TITLE
the color does not change 

### ISSUE THREAD

**Issue by mohammedAliGW** [paytabscom/flutter-sdk-bridge#27]

**Comment by AmmanAhmed786** [comment]
> 

Same issue with me

**Comment by KhaledAlramam** [comment]
Can you share more details about the issue?, which platform for example

**Comment by mohammedAliGW** [comment]
> 

Android 
i can't find the string that i should override !

**Comment by mohammedAliGW** [comment]
i made a clone of the package and modified it 

but it will be hard to track if it has an update or not i hope you fix the Android config in the next update.
Best of luck

**Comment by KhaledAlramam** [comment]
What modification did you make ?
And for the colors part you can create a color res file in the android folder, then add the attribute you want to override and you can find all the attributes here in the readme file:
https://github.com/paytabscom/flutter-sdk-bridge#android-theme

**Comment by mohammedAliGW** [comment]
> What modification did you make ? And for the colors part you can create a color res file in the android folder, then add the attribute you want to override and you can find all the attributes here in the readme file: https://github.com/paytabscom/flutter-sdk-bridge#android-theme

thank you 
thats better
i hope you add the option to override the back Button color

**Comment by AmmanAhmed786** [comment]
> What modification did you make ? And for the colors part you can create a color res file in the android folder, then add the attribute you want to override and you can find all the attributes here in the readme file: https://github.com/paytabscom/flutter-sdk-bridge#android-theme

Can you please guide me how to add the attribute I want to override. And where in the android folder to add my color res file

**Comment by mohammedAliGW** [comment]
> > What modification did you make ? And for the colors part you can create a color res file in the android folder, then add the attribute you want to override and you can find all the attributes here in the readme file: https://github.com/paytabscom/flutter-sdk-bridge#android-theme
> 
> Can you please guide me how to add the attribute I want to override. And where in the android folder to add my color res file

sorry i didn't see your comment 

you add the file like the pic and add the tags inside it 

![image](https://user-images.githubusercontent.com/88273182/150678278-b3f92302-62aa-49f3-aa20-d6d11deb044c.png)

![image](https://user-images.githubusercontent.com/88273182/150678330-4feb62eb-5b89-4846-979d-45863ca9ba1f.png)

**Comment by AmmanAhmed786** [comment]
> > > What modification did you make ? And for the colors part you can create a color res file in the android folder, then add the attribute you want to override and you can find all the attributes here in the readme file: https://github.com/paytabscom/flutter-sdk-bridge#android-theme
> > 
> > 
> > Can you please guide me how to add the attribute I want to override. And where in the android folder to add my color res file
> 
> sorry i didn't see your comment
> 
> you add the file like the pic and add the tags inside it
> 
> ![image](https://user-images.githubusercontent.com/88273182/150678278-b3f92302-62aa-49f3-aa20-d6d11deb044c.png)
> 
> ![image](https://user-images.githubusercontent.com/88273182/150678330-4feb62eb-5b89-4846-979d-45863ca9ba1f.png)

Thanks for helping!!
