### ISSUE TITLE
what is the deferent between Flutter PayTabs Bridge Emulator and flutter_paytabs_sdk 

### ISSUE THREAD

**Issue by Eng-MohamedGadala** [paytabscom/flutter-sdk-bridge#3]
Hi dear Developers,
what is the deferent between Flutter PayTabs Bridge Emulator and flutter_paytabs_sdk?
what is the best choice For the Flutter mobile app?

**Comment by devmfouad** [comment]
i need answer for this question also

**Comment by mohamedkhairy953** [comment]
flutter_paytabs_sdk is a native dart library but it is not complete so you need to use the bridge emulator
