### ISSUE TITLE
App crashes in release mode

### ISSUE THREAD

**Issue by matiullah-netlinks** [paytabscom/flutter-sdk-bridge#4]
After cloning the example project and building the apk using `flutter build apk` command the app crashed.

Steps to reproduce
1- Clone the example project
2- Run `flutter build apk`
3- Open the app and click the Pay with PayTabs

**Comment by mohamedkhairy953** [comment]
Hello 
I have walked through the steps but no crashes happened on my device 
Please provide us with more info like which device you use, the SDK version, maybe the stack trace of the crash if you have it
and the version of the aar file 

In the meantime, I will do some search to figure out what could be the cause.

**Comment by matiullah-netlinks** [comment]
@mohamedkhairy953 I'm using your own example project and my mobile android version is 9.

**Comment by matiullah-netlinks** [comment]
@mohamedkhairy953 It is working while development but when I build the release version it crashes

**Comment by mohamedkhairy953** [comment]
Do you enable the obfuscation

**Comment by matiullah-netlinks** [comment]
@mohamedkhairy953 Couldn't get you

**Comment by mohamedkhairy953** [comment]
Does the problem occurs in ios? And could you provide us with the logs.

**Comment by matiullah-netlinks** [comment]
@mohamedkhairy953 I haven't tested with iOS, because it is a released version I don't have access to the logs

**Comment by mohamedkhairy953** [comment]
[paytabs_sdk.zip](https://github.com/paytabscom/flutter-sdk-bridge/files/6056488/paytabs_sdk.zip)
please download the above aar file and replace it in this path:  ..\flutter-sdk-bridge\android\paytabs_sdk
and let me know the result

**Comment by matiullah-netlinks** [comment]
@mohamedkhairy953 I replaced it but still the app crashes

**Comment by matiullah-netlinks** [comment]
@mohamedkhairy953 But it is working fine when I run the app with `flutter run --release` command

**Comment by mohamedkhairy953** [comment]
hello 
Please try the new version 1.0.6 and let me know

**Comment by matiullah-netlinks** [comment]
@mohamedkhairy953 thank you, it is working now
