### ISSUE TITLE
Where to add the call back url?

### ISSUE THREAD

**Issue by AbdelrahmanMohamedEmam** [paytabscom/flutter-sdk-bridge#42]
I want to add the call bak url to provide a response to the server side after transaction finishes, as provided in the official [documentation](https://support.paytabs.com/en/support/solutions/articles/60000687835-what-are-the-five-5-ways-of-receiving-transaction-response-#2---Callback-Response).

**Comment by Yasoury** [comment]
same here

**Comment by naseeem** [comment]
same here

**Comment by mohamed3laily** [comment]
same here, where to add the callback webhook URL, the IPN works with the server API only and not with the mobile SDK
