### ISSUE TITLE
Error: Request must be in json format with content type application/json

### ISSUE THREAD

**Issue by amerblackbird** [paytabscom/flutter-sdk-bridge#47]
I/System.out(18856): payment_sdk_Logs : {"callback":"none","card_details":{"cvv":"---","expiry_month":2,"expiry_year":2027,"pan":"54983838********"},"cart_amount":20.0,"cart_currency":"SAR","cart_description":"Flowers","cart_id":"12433","customer_details":{"city":"jeddah","country":"sa","email":"email@domain.com","ip":"255.255.255.255","name":"John Smithes","phone":"0522222222","state":"jeddah","street1":"st. 12","zip":"12345"},"paypage_lang":"DEFAULT","profile_id":"-----","return":"https://ptsdk-return.paytabs.com/----------","shipping_details":{"city":"jeddah","country":"sa","email":"email@domain.com","ip":"","name":"John Smith","phone":"0522222222","state":"jeddah","street1":"st. 12","zip":"12345"},"tran_class":"recurring","tran_type":"sale","device_info":{"device_id":"","app_id":"com.example.payments","platform":"Android","brand":"samsung","model":"SM-M515F","carrier":"","os":"12","version":"12","app_version":"1.0.0","sdk_version":"6.2.10","timestamp":"1654420211918","screen_width":"1080","screen_height":"2400","app_lang":"en","device_lang":"en","connection":"wifi"}}

**Comment by potato-media990** [comment]
any update for this issue ?

**Comment by potato-media990** [comment]
check : 
https://support.paytabs.com/en/support/solutions/articles/60000715967--e-request-must-be-in-json-format-with-content-type-application-json
