### ISSUE TITLE
Attempt to present which is already presenting <PKPaymentAuthorizationViewController: 0x11e1f6a50>

### ISSUE THREAD

**Issue by NawafKartr** [paytabscom/flutter-sdk-bridge#48]
Hi team

I'm trying to use the package to enable Apple Pay in our flutter app. Most of the time it works great, but usually an issue comes up where the Apple Pay dialogue is not presented, and the following error message is shown in the debug terminal:

Attempt to present <PKPaymentAuthorizationViewController: 0x12f0a2aa0> on <FlutterViewController: 0x109824400> (from <FlutterViewController: 0x109824400>) which is already presenting <PKPaymentAuthorizationViewController: 0x11e1f6a50>.

Is there a quick fix that we can use to force the view controller to close and re-open again?

Thanks

**Comment by mualgo** [comment]
I have almost the same issue with the IOS device. Open the Pay card or Apple Pay dialog once or twice. After that give the same error. If anyone has the same and knows the best solution kindly share.


 Attempt to present <PKPaymentAuthorizationViewController: 0x125a26640> on <FlutterViewController: 0x11e01d200> (from <FlutterViewController: 0x11e01d200>) which is already presenting <PKPaymentAuthorizationViewController: 0x11ddc5a60>.
