### ISSUE TITLE
Error when building Pt_Ios example

### ISSUE THREAD

**Issue by MahmoudMB** [paytabscom/flutter-sdk-bridge#5]
Dear Team, 

I cannot run the example for the IOS, and this error appears to me

<img width="859" alt="Screen Shot 2021-03-27 at 12 01 06 AM" src="https://user-images.githubusercontent.com/23612742/112694667-c87e7700-8e93-11eb-83cf-3f5f9519f1fe.png">

**Comment by MahmoudMB** [comment]
@MuhamedAdly @mustafaanan

**Comment by mohamedkhairy953** [comment]
pt_ios branch was in the development phase,
you can checkout to pt2 branch now
