### ISSUE TITLE
Validation in iOS ?

### ISSUE THREAD

**Issue by madatr** [paytabscom/flutter-sdk-bridge#63]
Why don't you have any validation features for the input data, if a user clicks pay now and some info is missing or incorrect there is no validation or feedback such as a red border around the field with the issue or a pop up.

This is very confusing and not considered a good practice.

Also, the way you have implemented the FlutterPaytabsBridge.startCardPayment method is not convenient as it does not return a future with the payment result.

Thanks,

**Comment by madatr** [comment]
Any news on this?

**Comment by naseeem** [comment]
+1 please show the validation message

**Comment by karimSalahx** [comment]
+1 validation is working on android, just make it the same on iOS, as it is a critical feature to have

**Comment by madatr** [comment]
any progress on this? this a a vital feature and is a majour hindrance for users
