### ISSUE TITLE
Authentication failed. Check authentication header

### ISSUE THREAD

**Issue by ashekelahe** [paytabscom/flutter-sdk-bridge#64]
**Issue:** {message: Authentication failed. Check authentication header., code: 0, status: error}

**Payment Type:** Card Payment

**Payment Body:**
{pt_profile_id: 107706, pt_client_key: CMKMVG-M7QQ6T-KDD7KG-6QRBVT, pt_server_key: STJN6T9W9J-JGKDDTK6M2-MMZDDGBNMN, pt_screen_title: Pay with Card, pt_merchant_name: Feni Foodies, pt_amount: 100.0, pt_currency_code: EGP, pt_tokenise_type: merchantMandatory, pt_token_format: null, pt_token: null, pt_transaction_reference: null, pt_cart_id: 12433, pt_cart_description: My Product, pt_merchant_country_code: EG, pt_samsung_pay_token: null, pt_billing_details: {pt_name_billing: Ashek Elahe, pt_email_billing: ashek@6amtech.com, pt_phone_billing: +97311111111, pt_address_billing: Feni, Bangladesh, pt_country_billing: EG, pt_city_billing: dubai, pt_state_billing: dubai, pt_zip_billing: 12345}, pt_shipping_details: {pt_name_shipping: Ashek Elahe, pt_email_shipping: ashek@6amtech.com, pt_phone_shipping: +97311111111, pt_address_shipping: Feni, Bangladesh, pt_country_shipping: EG, pt_city_shipping: dubai, pt_state_shipping: dubai, pt_zip_shipping: 12345}, pt_language: null, pt_show_billing_info: true, pt_show_shipping_info: null, pt_force_validate_shipping: false, pt_ios_theme: {pt_ios_logo: /Users/ashek/Library/Developer/CoreSimulator/Devices/CC8F8181-D3EF-4C82-900F-8DBED495E2A6/data/Containers/Data/Application/B2BEDAF6-8664-45C2-A0CB-2C3DF31782F2/Documents/logo.png, pt_ios_primary_color: null, pt_ios_primary_font_color: null, pt_ios_secondary_color: null, pt_ios_secondary_font_color: null, pt_ios_stroke_color: null, pt_ios_button_color: null, pt_ios_button_font_color: null, pt_ios_title_font_color: null, pt_ios_background_color: null, pt_ios_placeholder_color: null, pt_ios_primary_font: null, pt_ios_secondary_font: null, pt_ios_stroke_thinckness: null, pt_ios_inputs_corner_radius: null, pt_ios_button_font: null, pt_ios_title_font: null}, pt_merchant_id: null, pt_simplify_apple_pay_validation: null, pt_hide_card_scanner: null, pt_transaction_class: null, pt_transaction_type: null, pt_apms: aman, pt_link_billing_name: true}

**Comment by KhaledAlramam** [comment]
Please, double check your currency code and country code

**Comment by ashekelahe** [comment]
@KhaledAlramam Thank you for your response.
Can you please provide me a country code and currency code so that I can test?

**Comment by KhaledAlramam** [comment]
Each profile has its own currency and country code associated with profile id, that could be found on paytabs merchant dashboard.

**Comment by ashekelahe** [comment]
@KhaledAlramam 

Now its okay with currency but it fails transaction:

flutter: ======> Response [false] : Error occurred
flutter: {isSuccess: false, paymentInfo: {paymentDescription: 4000 00## #### 0002, cardType: Credit, payment_method: Visa, expiryMonth: 12, cardScheme: Visa, expiryYear: 2025}, trace: PMNT0601.646991B9.000269E1, isPending: false, cartID: 12433, tranCurrency: JOD, isOnHold: false, transactionReference: TST2314101598899, merchantId: 52717, cartAmount: 100.000, isProcessed: true, isAuthorized: false, paymentResult: {responseCode: 202, transactionTime: 2023-05-21T03:36:26Z, responseMessage: Invalid card security code (CVV), responseStatus: E}, cartDescription: My Product, cartCurrency: JOD, profileId: 107706, billingDetails: {phone: +97311111111, city: Jordan, email: ashek@6amtech.com, countryCode: JO, zip: 12345, addressLine: Feni, Bangladesh, name: Ashek Elahe}, serviceId: 7, transactionType: Sale, tranTotal: 100.000}

**Comment by KhaledAlramam** [comment]
The error says wrong cvv,
What cvv did you enter?

**Comment by ashekelahe** [comment]
@KhaledAlramam 
I have set CVV as 123 which is right CVV because I can see it in my test cards section.

![Simulator Screenshot - iPhone 13 Pro Max - 2023-05-21 at 14 54 36](https://github.com/paytabscom/flutter-sdk-bridge/assets/117248927/3839c97d-f853-4fdc-be64-276b3758553c)

**Comment by KhaledAlramam** [comment]
Make sure the selected profile credentials are test profile

**Comment by ashekelahe** [comment]
@KhaledAlramam 

It is already in test mode
![Screenshot 2023-05-21 at 3 10 13 PM](https://github.com/paytabscom/flutter-sdk-bridge/assets/117248927/54b2d83c-5a6e-4eef-8bb5-a8f3b0882b83)

**Comment by KhaledAlramam** [comment]
You can start a support ticket on the paytabs site, they will give you better assistance as they have access to your data
