### ISSUE TITLE
Payment screen not opening

### ISSUE THREAD

**Issue by OMARIHAMZA** [paytabscom/flutter-sdk-bridge#7]
I'm trying to integrate `flutter_paytabs_bridge: ^2.0.1-beta` into my Flutter app.

I added the config parameters as described in [the documentation](https://pub.dev/packages/flutter_paytabs_bridge), but when I try to start the payment nothing happens in the app!

P.S.  
 - The library requested phone permissions
 - I'm running on Android 10
 - These lines get printed in the terminal

`I/System.out(  728): PaymentSdkFragment onCreateView: PaymentSdkConfigurationDetails(profileId=63854, serverKey=****-****-****, clientKey=****-****-****-****, billingDetails=PaymentSdkBillingDetails(city=city, countryCode=country, email=billing email, name=billing name, phone=billing phone, state=state, addressLine=address line, zip=zip code), shippingDetails=com.payment.paymentsdk.integrationmodels.PaymentSdkShippingDetails@726ec3a, locale=AR, cartId=25, currencyCode=SAR, cartDescription=cart desc, transactionType=sale, transactionClass=ecom, amount=20.0, screenTitle=Pay with Card, customerIp=255.255.255.255, tokeniseType=NONE, tokenFormat=null, token=, transactionReference=, logo=null, showBillingInfo=false, showShippingInfo=false, forceShippingInfoValidation=false, merchantCountry=SA, hideCardScanner=false)
D/ForceDarkHelper(  728): updateByCheckExcludeList: pkg: com.rqwah.user activity: com.payment.paymentsdk.PaymentSdkActivity@31a32e7`

Thanks in advance!

**Comment by mohamedkhairy953** [comment]
Hello 
Did you receive anything from the flutter cllback 
It may be some validation error which returns to you through the callback

**Comment by OMARIHAMZA** [comment]
Hello Mohamed, 

Thanks for your response. 

I printed the callback result and I got this error:

`{code: -1, data: null, message: Invalid merchant country code (it should be alpha-2 ISO code), status: error}`

My config is as follows:

`var configuration = PaymentSdkConfigurationDetails(
      profileId: "myid",
      serverKey: "secret-secret-secret",
      clientKey: "secret-secret-secret-secret",
      cartId: "25",
      cartDescription: "cart desc",
      merchantName: "Mhd",
      screentTitle: "Pay with Card",
      billingDetails: billingDetails,
      shippingDetails: shippingDetails,
      locale: PaymentSdkLocale.EN,
      amount: 20.0,
      currencyCode: "SAR",
      merchantCountryCode: "SA",
    );`

What is the correct alpha-2 ISO code for Saudi Arabia?

**Comment by mohamedkhairy953** [comment]
SA

**Comment by mohamedkhairy953** [comment]
I will check this might be a problem in the validation

**Comment by OMARIHAMZA** [comment]
OK, thanks.

Please do let me know once you find the cause of the problem :)

**Comment by mohamedkhairy953** [comment]
Hello Omar, Could you please tell me what device you are using to reproduce this issue, and do me a favor and try on another device and let me know.

**Comment by OMARIHAMZA** [comment]
I tested it on 2 devices: Xiaomi mi mix 3 & AVD (Pixel 3a API 29).

The issue occurs in both devices.

**Comment by mohamedkhairy953** [comment]
We've published a new version 2.0.2-beta, please upgrade your version and try again

**Comment by OMARIHAMZA** [comment]
I upgraded the library to `flutter_paytabs_bridge: ^2.0.2-beta`

Nothing has changed.

`{code: -1, data: null, message: Invalid billing country code, status: error}`

**Comment by mohamedkhairy953** [comment]
Billing country must be 2 digits iso
Your logcat shows that you are passing it "country"

**Comment by OMARIHAMZA** [comment]
I thought the problem was from the config object! Didn't know that the address object was causing it!

Thank you very much Mohamed for your help!

**Comment by mohamedkhairy953** [comment]
You are welcome
