### ISSUE TITLE
Paytabs it is giving “Duplicate Request” Error

### ISSUE THREAD

**Issue by JaveedIshaq** [paytabscom/flutter-sdk-bridge#77]
We are Paytabs payment-gateway, while test credentials, it worked pretty well,

We are Paytabs payment-gateway, (flutter-sdk-bridge) while using test credentials, it worked pretty well,

but on LIVE account of Paytabs it is giving “Duplicate Request” Error

{trace: PMNT0201.663851C3.00064259, code: 4, message: Duplicate Request, status: error}

**Comment by MuhamedAdly** [comment]
Please make sure you are using the latest version of the plugin and that there are no network problems.
