### ISSUE TITLE
When add package to pubspec.yaml, project crash while build and return this error

### ISSUE THREAD

**Issue by hosaaam** [paytabscom/flutter-sdk-bridge#78]
![WhatsApp Image 2024-05-25 at 1 01 17 PM](https://github.com/paytabscom/flutter-sdk-bridge/assets/85756298/b6948478-2e96-4bdf-943f-276061e0624b)

flutter doctor 
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.19.4, on Microsoft Windows [Version 10.0.19045.4412], locale en-US)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[√] Chrome - develop for the web
[X] Visual Studio - develop Windows apps
    X Visual Studio not installed; this is necessary to develop Windows apps.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components
[√] Android Studio (version 2023.3)
[√] Connected device (4 available)
[√] Network resources

! Doctor found issues in 1 category.

**Comment by khaflh** [comment]
same for me

**Comment by muhammadalkady** [comment]
Could you please try running the sample app to see if it has this issue?

**Comment by hosaaam** [comment]
> Could you please try running the sample app to see if it has this issue?

same isuue

**Comment by muhammadalkady** [comment]
I can run our sample locally. Please share `flutter doctor` command output.

**Comment by muhammadalkady** [comment]
Please upgrade PayTabs Flutter plugin to:
`flutter_paytabs_bridge: ^2.6.12`
Additionally, upgrade the Kotlin version to:
`id "org.jetbrains.kotlin.android" version "1.9.23" apply false`. You can find it in the android project directory in `settings.gradle`

**Comment by hosaaam** [comment]
> Please upgrade PayTabs Flutter plugin to: `flutter_paytabs_bridge: ^2.6.12` Additionally, upgrade the Kotlin version to: `id "org.jetbrains.kotlin.android" version "1.9.23" apply false`. You can find it in the android project directory in `settings.gradle`

thanks a lot , new version works fine
