### ISSUE TITLE
app dosn't run when add plugins in dependencies

### ISSUE THREAD

**Issue by AmirAhmedDarrag** [paytabscom/flutter-sdk-bridge#79]
After add plugins in dependencies flutter project not run and give below error

ERROR:/Users/amir/.gradle/caches/transforms-3/f59d0fe8a4989db0778358dd7ee2dcf1/transformed/lifecycle-livedata-core-2.8.0-runtime.jar: D8: java.lang.NullPointerException

**Comment by muhammadalkady** [comment]
Please upgrade PayTabs Flutter plugin to:
`flutter_paytabs_bridge: ^2.6.12`
Additionally, upgrade the Kotlin version to:
`id "org.jetbrains.kotlin.android" version "1.9.23" apply false`. You can find it in the android project directory in `settings.gradle`
