### ISSUE TITLE
Request must be in JSON format with content type application/json

### ISSUE THREAD

**Issue by OMARIHAMZA** [paytabscom/flutter-sdk-bridge#8]
Hello again!

I'm trying to submit a test payment (using the test cards provided in Paytabs documentation) but whenever I hit the 'Pay Now' button a toast is being displayed with the message (Request must be in JSON format with content-type application/json).

Could you please resolve the issue asap?

Library version: `flutter_paytabs_bridge: ^2.0.3-beta`

**Comment by mohamedkhairy953** [comment]
I think you are using the client key and the server key of the web api not the mobile sdk 
Please contact customercare@paytabs.com to provide you with the mobile sdk keys.
