### ISSUE TITLE
Button Text Not Visible in Close Payment Dialog

### ISSUE THREAD

**Issue by ibrahimmohamed2411** [paytabscom/flutter-sdk-bridge#84]
![Screenshot_1731930765](https://github.com/user-attachments/assets/e816bba7-f66a-4f08-9bd0-7840997910ef)
The issue appears with version: 2.6.19

**Comment by muhammadalkady** [comment]
Fixed. Please upgrade to 2.6.20

**Comment by ibrahimmohamed2411** [comment]
The bug still exist
