### ISSUE TITLE
MaterialButton inflation in Flutter release builds.

### ISSUE THREAD

**Issue by ibrahimmohamed2411** [paytabscom/flutter-sdk-bridge#85]
E/AndroidRuntime(32002): FATAL EXCEPTION: main
E/AndroidRuntime(32002): Process: com.example.app, PID: 32002
E/AndroidRuntime(32002): android.view.InflateException: Binary XML file line #208 in com.example.app:layout/fragment_payment_sdk_credit_card: Binary XML file line #208 in com.example.app:layout/fragment_payment_sdk_credit_card: Error inflating class com.google.android.material.button.MaterialButton
E/AndroidRuntime(32002): Caused by: android.view.InflateException: Binary XML file line #208 in com.example.app:layout/fragment_payment_sdk_credit_card: Error inflating class com.google.android.material.button.MaterialButton

**Comment by muhammadalkady** [comment]
Hi @ibrahimmohamed2411 I can run the sample in release mode without no issues. Please provide minimal sample the reproduces the issue.
