### ISSUE TITLE
Request must be in JSON format with content type application/json

### ISSUE THREAD

**Issue by ozzi0032** [paytabscom/flutter-sdk-bridge#9]
I am using the 2.0.3-beta and trying to implement through demo example with my credentials but this error is returned
"Request must be in JSON format with content type application/json"

I am also attaching the API Debug console snapshot

![image](https://user-images.githubusercontent.com/41320366/115140175-5858b080-a04f-11eb-9741-ca2aafea5d77.png)

![image](https://user-images.githubusercontent.com/41320366/115140147-424af000-a04f-11eb-9516-3be941f310ed.png)

**Comment by mohamedkhairy953** [comment]
Please find your problem here with the correct answer.

https://github.com/paytabscom/paytabs-android-library-sample/blob/PT2/common_issues.md
